version: '2.1'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes: 
      - mysql-data:/var/lib/mysql
  web:
    image: test-app
    build: .
    environment:
      NODE_ENV: production
    volumes: 
      - web-data:/storage
    command: npm start
volumes: 
  mysql-data:
  web-data: